import = [
	#"~/.config/alacritty/catpuccin-frappe.toml"
  #"~/.config/alacritty/rose-pine-moon.toml"
  #"~/.config/alacritty/solarized_dark.toml"
  "~/.config/alacritty/material_theme.toml"
  #"~/.config/alacritty/gruvbox_dark.toml"
]
live_config_reload = true

[window]
	opacity = 0.8
	padding = {x=5,y=5}
	decorations = "None"
[font]
	normal = {family = "terminal-font"}
	size = 14.0

[env]
	TERM = "xterm-256color"

[cursor]
  style = {shape = "Beam", blinking = "On"}
