
[window]
	opacity = 0.8
	padding = {x=5,y=5}
	decorations = "None"
[font]
	normal = {family = "terminal-font"}
	size = 14.0

[env]
	TERM = "xterm-256color"

[cursor]
	style = {shape = "Beam", blinking = "On"}
	vi_mode_style = {shape = "Block"}

[general]
live_config_reload = true
import = [
	#"~/.config/alacritty/themes/catppuccin-frappe.toml"
	#"~/.config/alacritty/themes/catppuccin-mocha.toml"
	"~/.config/alacritty/themes/rose-pine-moon.toml"
	#"~/.config/alacritty/themes/solarized_dark.toml"
	#"~/.config/alacritty/themes/material_theme.toml"
	#"~/.config/alacritty/themes/gruvbox_dark.toml"
	#"~/.config/alacritty/themes/monokai_pro.toml"
	#"~/.config/alacritty/themes/monokai.toml"
]
