import = [
	"~/.config/alacritty/catpuccin-frappe.toml"
]

[window]
	opacity = 0.8
[font]
	normal = {family = "CaskaydiaCove Nerd Font", style = "Regular"}
	size = 14.0

[env]
	TERM = "xterm-256color"
